name: Build & Release

# Trigger on push to master branch or with a tag
on:
  push:
    branches:
      - '**'
    tags:
      - '0.*'

# If previous workflow is still running, we push again, we will cancel the previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: Android
            os: ubuntu-latest
            artifact_name: release-Android
            artifact_path: build/app/outputs/apk/release/*.apk
          - target: Windows
            os: windows-latest
            artifact_name: release-Windows
            artifact_path: build/windows/*.zip
          - target: Linux
            os: ubuntu-latest
            artifact_name: release-Linux
            artifact_path: build/linux/*.deb
          - target: iOS
            os: macos-latest
            cache_pod_key: ios-pods
            cache_pod_path: ios/Pods
            cache_pod_restore_keys_hash_file: ios/Podfile.lock
            artifact_name: release-iOS
            artifact_path: build/**/*.ipa
          - target: macOS
            os: macos-latest
            cache_pod_key: macos-pods
            cache_pod_path: macos/Pods
            cache_pod_restore_keys_hash_file: macos/Podfile.lock
            artifact_name: release-macOS
            artifact_path: ./*.dmg
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    runs-on: ${{ matrix.os }}
    env:
      FLUTTER_VERSION: 3.29.2
    steps:
      # Checkout branch
      - name: Checkout
        uses: actions/checkout@v4
      
      # Update version number
      - name: Update version number
        shell: bash
        run: |
          # 配置 Git
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # 确保与远程仓库同步
          git pull origin ${GITHUB_REF#refs/heads/} --rebase
          
          # 读取当前版本号
          CURRENT_VERSION=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2)
          echo "Current version: $CURRENT_VERSION"
          
          # 分割版本号
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
          
          # 增加补丁版本号
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "New version: $NEW_VERSION"
          
          # 更新 pubspec.yaml
          case "$(uname -s)" in
            Darwin*)    # macOS
              sed -i '' "s/^version: .*$/version: $NEW_VERSION/" pubspec.yaml
              ;;
            *)          # Linux, Windows
              sed -i "s/^version: .*$/version: $NEW_VERSION/" pubspec.yaml
              ;;
          esac
          
          # 提交并推送更改
          git add pubspec.yaml
          git commit -m "chore: bump version to $NEW_VERSION [skip ci]"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
      
      # Setup Android keystore (for Android)
      - name: Setup Android keystore
        if: matrix.target == 'Android'
        run: |
          echo "${{ secrets.ENCODED_KEYSTORE }}" | base64 -di > android/app/upload-keystore.jks
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties
      
      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      # Cache CocoaPods (for iOS/macOS)
      - name: Cache Pod
        if: matrix.cache_pod_key != null
        uses: actions/cache@v4
        with:
          key: ${{ matrix.cache_pod_key }}
          path: ${{ matrix.cache_pod_path }}
          restore-keys: ${{ matrix.cache_pod_key }}-${{ hashFiles(matrix.cache_pod_restore_keys_hash_file) }}
      
      # Setup JDK for Android
      - name: Setup JDK 17 (Android)
        if: matrix.target == 'Android'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      
      # Xcode build for iOS/macOS
      - name: Build Xcode (iOS/macOS)
        if: matrix.os == 'macos-latest'
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release
      
      # Flutter Pub Get
      - name: Flutter Pub Get
        run: |
          git config --global core.longpaths true
          flutter pub get
      
      # Get app version
      - name: Get app version
        id: get_version
        run: |
          echo "::set-output name=version::$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2)"
      
      # Build Android .apk
      - name: Build Android
        if: matrix.target == 'Android'
        run: |
          flutter build apk --release --split-per-abi
          cd build/app/outputs/apk/release
          mv app-arm64-v8a-release.apk NipaPlay-${{ steps.get_version.outputs.version }}-arm64-v8a.apk
          mv app-armeabi-v7a-release.apk NipaPlay-${{ steps.get_version.outputs.version }}-armeabi-v7a.apk
          mv app-x86_64-release.apk NipaPlay-${{ steps.get_version.outputs.version }}-x86_64.apk
      
      # Build iOS .ipa
      - name: Build iOS
        if: matrix.target == 'iOS'
        run: |
          cd ios
          pod update
          cd ..
          flutter build ios --release --no-codesign
          sh thin-payload.sh build/ios/iphoneos/*.app
          cd build
          mkdir -p Payload
          mv ios/iphoneos/*.app Payload
          zip -9 NipaPlay_${{ steps.get_version.outputs.version }}.ipa -r Payload
      
      # Build macOS .dmg
      - name: Build macOS
        if: matrix.target == 'macOS'
        run: |
          cd macos
          pod update
          cd ..
          sh dmg.sh
      
      # Build Windows .zip
      - name: Build Windows
        if: matrix.target == 'Windows'
        run: |
          flutter build windows --release
          $DestDir = "build\windows\NipaPlay_${{ steps.get_version.outputs.version }}"
          $SrcDir = "build\windows\x64\runner\Release"
          New-Item -Path $DestDir -ItemType Directory
          Copy-Item $SrcDir\* -Recurse $DestDir
          Copy-Item -Filter *.dll -Path windows\* -Destination $DestDir -Force
          Compress-Archive $DestDir build\windows\NipaPlay_${{ steps.get_version.outputs.version }}_Windows.zip
      
      # Build Linux .deb
      - name: Build Linux .deb
        if: matrix.target == 'Linux'
        run: |
          # 安装 mpv 和其他依赖
          sudo apt-get update -y
          sudo apt-get install -y mpv libmpv-dev pkg-config clang cmake libgtk-3-dev ninja-build libasound2-dev libass-dev
          
          # 构建 Flutter for Linux
          flutter config --enable-linux-desktop
          flutter build linux --release
          
          # 检查构建产物目录
          echo "Listing build output:"
          ls build/linux/x64/release/
          ls build/linux/x64/release/bundle/
          
          # 创建 .deb 包
          mkdir -p build/linux/NipaPlay-${{ steps.get_version.outputs.version }}-Linux-amd64
          cd build/linux/NipaPlay-${{ steps.get_version.outputs.version }}-Linux-amd64
          mkdir -p opt/nipaplay
          mkdir -p usr/share/applications
          mkdir -p usr/share/icons/hicolor/512x512/apps
          cp -r ../x64/release/bundle/* opt/nipaplay
          cp -r ../../../assets/linux/DEBIAN .
          chmod 0755 DEBIAN/postinst
          chmod 0755 DEBIAN/postrm
          cat > DEBIAN/control <<EOF
          Maintainer: madoka773 <valigarmanda55@gmail.com>
          Package: NipaPlay
          Version: ${{ steps.get_version.outputs.version }}
          Section: x11
          Priority: optional
          Architecture: amd64
          Essential: no
          Installed-Size: 34648
          Description: A cross platform danmaku video player.
          Homepage: https://github.com/MCDFsteve/NipaPlay-Reload
          Depends: ffmpeg, libass9
          EOF
          cp ../../../assets/linux/io.github.MCDFsteve.NipaPlay-Reload.desktop usr/share/applications
          cp ../../../assets/images/logo512.png usr/share/icons/hicolor/512x512/apps/io.github.MCDFsteve.NipaPlay-Reload.png
          cd ..
          dpkg-deb --build --root-owner-group NipaPlay-${{ steps.get_version.outputs.version }}-Linux-amd64
          
      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}

  Publish:
    name: Publish
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Make tmp dir
        run: mkdir /tmp/artifacts
      
      - name: Download all Artifacts
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts
      
      - name: List all Artifacts
        run: ls -R /tmp/artifacts
      
      - name: Get commit message
        id: commit_message
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
      
      - name: Get commit range
        id: commit_range
        run: |
          echo "range=$(git log --pretty=format:"- %s" -n 10)" >> $GITHUB_OUTPUT
      
      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release v${{ needs.Build.outputs.version }}
          body: |
            ## 版本 v${{ needs.Build.outputs.version }}
            
            ### 主要更新
            ${{ steps.commit_message.outputs.message }}
            
            ### 最近更新内容
            ${{ steps.commit_range.outputs.range }}
            
            ### 构建信息
            - 构建时间: ${{ github.event.head_commit.timestamp }}
            - 提交: ${{ github.sha }}
            - 分支: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: /tmp/artifacts/release-Android/*.apk,/tmp/artifacts/release-iOS/*.ipa,/tmp/artifacts/release-macOS/*.dmg,/tmp/artifacts/release-Windows/*.zip,/tmp/artifacts/release-Linux/*.deb
          artifactErrorsFailBuild: true
          replacesArtifacts: true
